apiVersion: apps/v1
kind: Deployment
metadata:
  name: pz41-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pz41-app
  template:
    metadata:
      labels:
        app: pz41-app
    spec:
      containers:
        - name: pz41-app
          image: pz41-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:h2:mem:testdb"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "admin"
            - name: SPRING_FLYWAY_ENABLED
              value: "false"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"
            - name: SPRING_JPA_DATABASE_PLATFORM
              value: "org.hibernate.dialect.H2Dialect"
            - name: JWT_SECRET
              value: "KgcPh88SUiCubeT5YeiyK7mIIlPCywg/+Ths1DMEHkucfyH6mFr8gwEiH/PnPmx8rdDymZkpXlEjisY+h8yLkA=="