apiVersion: v1
kind: Service
metadata:
  name: pz41-app-service
spec:
  type: NodePort
  selector:
    app: pz41-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
